# Generated by Django 5.2.6 on 2025-09-13 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('footwear', 'Footwear'), ('accessories', 'Accessories'), ('supplements', 'Supplements'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('other', 'Other')], default='other', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('item_sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
