# Generated by Django 5.2.6 on 2025-09-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('footwear', 'Footwear'), ('accessories', 'Accessories'), ('supplements', 'Supplements'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('other', 'Other')], default='other', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('item_sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
